import React from "react";
import BarChart from "./BarChart";

const bars = [
  {
    title: "June 24",
    bookings: [
      {
        LfdNr: 27,
        Kunden_ID: 29,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-05T22:00:00.000Z",
        Beginn_Start: "2024-06-06T11:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-08T22:00:00.000Z",
        Ende_Start: "2024-06-09T15:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: null,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Angenendt, Sonnhard",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 25,
        Kunden_ID: 29,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-05T22:00:00.000Z",
        Beginn_Start: "2024-06-06T11:30:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-08T22:00:00.000Z",
        Ende_Start: "2024-06-09T15:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: null,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Angenendt, Sonnhard",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 28,
        Kunden_ID: 29,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-05T22:00:00.000Z",
        Beginn_Start: "2024-06-06T11:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-08T22:00:00.000Z",
        Ende_Start: "2024-06-09T15:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: null,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Angenendt, Sonnhard",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 26,
        Kunden_ID: 274,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-06T22:00:00.000Z",
        Beginn_Start: "2024-06-07T11:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-06T22:00:00.000Z",
        Ende_Start: "2024-06-07T15:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: null,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Zoller, Isbert",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 1,
        Kunden_ID: 11,
        Tier_ID: 1,
        Beginn_Datum: "2024-06-09T22:00:00.000Z",
        Beginn_Start: "2024-06-09T22:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-19T22:00:00.000Z",
        Ende_Start: "2024-06-19T22:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: 1,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Jörger, Gunther",
        Name1: "Pudel",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 2,
        Kunden_ID: 10,
        Tier_ID: 2,
        Beginn_Datum: "2024-06-09T22:00:00.000Z",
        Beginn_Start: "2024-06-09T22:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-19T22:00:00.000Z",
        Ende_Start: "2024-06-19T22:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: 1,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: 60,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Grüning, Pascal",
        Name1: "Pudel",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 3,
        Kunden_ID: 40,
        Tier_ID: 4,
        Beginn_Datum: "2024-06-11T22:00:00.000Z",
        Beginn_Start: "2024-06-11T22:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-07-01T22:00:00.000Z",
        Ende_Start: "2024-07-01T22:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: 1,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Perkins, Sigtraud",
        Name1: "Labrador",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 24,
        Kunden_ID: 181,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-12T22:00:00.000Z",
        Beginn_Start: "2024-06-13T11:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-19T22:00:00.000Z",
        Ende_Start: "2024-06-20T15:00:00.000Z",
        Ende_Zeitraum: 30,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: null,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Adam, Wendela",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 4,
        Kunden_ID: 50,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-17T22:00:00.000Z",
        Beginn_Start: "2024-06-17T22:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-21T22:00:00.000Z",
        Ende_Start: "2024-06-21T22:00:00.000Z",
        Ende_Zeitraum: 40,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: 1,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Teichert, Annette",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
      {
        LfdNr: 5,
        Kunden_ID: 50,
        Tier_ID: 5,
        Beginn_Datum: "2024-06-17T22:00:00.000Z",
        Beginn_Start: "2024-06-17T22:00:00.000Z",
        Beginn_Zeitraum: 30,
        Ende_Datum: "2024-06-21T22:00:00.000Z",
        Ende_Start: "2024-06-21T22:00:00.000Z",
        Ende_Zeitraum: 40,
        AufwandKlasse_ID: null,
        AufwandEinheiten: null,
        Quartier_ID: 1,
        Anmeld_am: null,
        Anmeld_Mitarbeiter_ID: null,
        Zusage_am: null,
        Storno_am: null,
        Storno_Mitarbeiter_ID: null,
        BuchStatus_ID: null,
        Level: 1,
        Bemerkungen: null,
        HinzuAm: null,
        HinzuDurch: null,
        BearbAm: null,
        BearbDurch: null,
        NameIntern: "Teichert, Annette",
        Name1: "Deutscher Schäferhund",
        Geburtstag: null,
        Geschlecht: null,
        Code: "Hu",
      },
    ],
  },
];

const App = () => {
  return (
    <div className="App">
      <h1>Responsive Horizontal Bar Chart with Date Headers and Grid Lines</h1>
      <BarChart bars={bars} />
    </div>
  );
};

export default App;
